pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("private-registry/my-service:${env.BUILD_NUMBER}")
                    docker.withRegistry('https://private-registry', '<creds>') {
                        docker.image("private-registry/my-service:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }
    //To automate Docker versioning
    stage('Build Docker Image') {
        steps {
            script {
                def version = "${env.BUILD_NUMBER}-${sh(script: 'git rev-parse --short HEAD', returnStdout: true)}"            
                docker.build("private-registry/my-service:${version}")
                docker.withRegistry('https://private-registry', 'creds') {
                    docker.image("private-registry/my-service:${version}").push()
                }
            }
        }
    }
    }
}